name: Go

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: run jq
      run: |
        curl -s -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod +x jq
        jq --version

        cov_data=$(curl -s -H "Authorization: 2d52a5c1-6ce6-4c27-976b-7a23de618b8a" \
                  https://codecov.io/api/gh/fundwit/skysight/commit/1fc1ca20973b2d362b7bb24b1169039f48825e59)

        parent_cov=$(echo $cov_data | jq -r .commit.parent_totals.c1)
        current_cov=$(echo $cov_data | jq -r .commit.totals.c)
        if [ "$current_cov" == "" ]; then
          echo  "error: coverage data not found"
          exit 1
        fi
        
        if [ "s$parent_cov" == "s" or "$parent_cov" == "null" ]; then
           echo "coverage of parent not found, set to 0"
           parent_cov=0
        fi
        
        echo "coverage change: ${parent_cov} => ${current_cov} " $(echo "$current_cov - $parent_cov" | bc)

        if [ `echo "${current_cov} < ${parent_cov}"|bc` -eq 1 ] ; then
          echo  "error: coverage of current commit must equal or greater than coverage of parent commit"
          exit 1
        fi
        
