name: Go

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: run jq
      run: |
        curl -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod +x jq
        jq --version
        curl -H "Authorization: 2d52a5c1-6ce6-4c27-976b-7a23de618b8a" \
                  https://codecov.io/api/gh/fundwit/skysight/commit/1fc1ca20973b2d362b7bb24b1169039f48825e59 > commit_coverage.json
        echo '-- coverage gate --'
        origin_cov=$(cat commit_coverage.json | jq .commit.parent_totals.c)
        new_cov=$(cat commit_coverage.json | jq .commit.totals.c)
        echo "new coverage: ${new_cov}, origin: ${origin_cov}, new coverage must euqal or greater thanorigin coverage"
        ((origin_cov <= new_cov))
        
