name: Go

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Kubernetes toolset
      uses: stefanprodan/kube-tools@v1.7.1
      
    - name: run jq
      run: |
        jq version
