name: Go

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: run jq
      run: |
        curl -o jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod +x jq
        jq --version
